# Generated by Django 2.2.4 on 2019-09-21 08:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("journal", "0001_initial_manual"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="squad",
            name="name",
        ),
    ]
