# Generated by Django 2.2.4 on 2019-10-11 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journal', '0006_auto_20191010_1126'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentattendancetype',
            name='name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
