# Generated by Django 2.2.4 on 2019-10-11 11:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("journal", "0008_auto_20191011_0931"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="curriculum",
            options={
                "managed": True,
                "verbose_name": "Расписание",
                "verbose_name_plural": "Расписание",
            },
        ),
        migrations.AlterModelOptions(
            name="squad",
            options={
                "managed": True,
                "verbose_name": "Взвод",
                "verbose_name_plural": "Взвода",
            },
        ),
        migrations.AlterModelTable(
            name="studentattendancetype",
            table="attendance_types",
        ),
    ]
