# Generated by Django 2.2.4 on 2019-11-02 18:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("journal", "0011_auto_20191101_1225"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="personalinfo",
            name="address",
        ),
        migrations.RemoveField(
            model_name="personalinfo",
            name="characteristic",
        ),
        migrations.AddField(
            model_name="personalinfo",
            name="birth_place",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="personalinfo",
            name="characteristic_first_year",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="personalinfo",
            name="characteristic_second_year",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="personalinfo",
            name="characteristic_third_year",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="personalinfo",
            name="commissariat",
            field=models.CharField(blank=True, max_length=512),
        ),
        migrations.AddField(
            model_name="personalinfo",
            name="conclusion",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="personalinfo",
            name="end_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="personalinfo",
            name="fact_address",
            field=models.CharField(blank=True, max_length=512),
        ),
        migrations.AddField(
            model_name="personalinfo",
            name="family_members",
            field=models.CharField(blank=True, max_length=512),
        ),
        migrations.AddField(
            model_name="personalinfo",
            name="family_status",
            field=models.CharField(blank=True, max_length=512),
        ),
        migrations.AddField(
            model_name="personalinfo",
            name="medical_report",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="personalinfo",
            name="passport_issued_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="personalinfo",
            name="reg_address",
            field=models.CharField(blank=True, max_length=512),
        ),
        migrations.AddField(
            model_name="personalinfo",
            name="service_rank",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name="personalinfo",
            name="start_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="personalinfo",
            name="passport_issued",
            field=models.CharField(blank=True, max_length=512),
        ),
        migrations.AlterField(
            model_name="student",
            name="squad",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="journal.Squad",
                verbose_name="Взвод",
            ),
        ),
    ]
