# Generated by Django 2.2.4 on 2019-11-08 07:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('journal', '0012_auto_20191102_1845'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personalinfo',
            name='student',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='journal.Student'),
        ),
    ]
