# Generated by Django 2.2.4 on 2019-11-08 08:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("journal", "0013_auto_20191108_0704"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="personalinfo",
            options={
                "managed": True,
                "verbose_name": "Персональные данные",
                "verbose_name_plural": "Персональные данные",
            },
        ),
        migrations.AlterField(
            model_name="personalinfo",
            name="birth_date",
            field=models.DateField(blank=True, null=True, verbose_name="Дата рождения"),
        ),
        migrations.AlterField(
            model_name="personalinfo",
            name="birth_place",
            field=models.TextField(blank=True, verbose_name="Место рождения"),
        ),
        migrations.AlterField(
            model_name="personalinfo",
            name="characteristic_first_year",
            field=models.TextField(
                blank=True, null=True, verbose_name="Характеристика за 2 курс"
            ),
        ),
        migrations.AlterField(
            model_name="personalinfo",
            name="characteristic_second_year",
            field=models.TextField(
                blank=True, null=True, verbose_name="Характеристика за 3 курс"
            ),
        ),
        migrations.AlterField(
            model_name="personalinfo",
            name="characteristic_third_year",
            field=models.TextField(
                blank=True, null=True, verbose_name="Характеристика за 4 курс"
            ),
        ),
        migrations.AlterField(
            model_name="personalinfo",
            name="commissariat",
            field=models.CharField(
                blank=True, max_length=512, verbose_name="Военкомат"
            ),
        ),
        migrations.AlterField(
            model_name="personalinfo",
            name="conclusion",
            field=models.TextField(
                blank=True, null=True, verbose_name="Категория годности"
            ),
        ),
        migrations.AlterField(
            model_name="personalinfo",
            name="end_date",
            field=models.DateField(
                blank=True, null=True, verbose_name="Окончание обучения"
            ),
        ),
        migrations.AlterField(
            model_name="personalinfo",
            name="fact_address",
            field=models.CharField(
                blank=True, max_length=512, verbose_name="Адрес фактический"
            ),
        ),
        migrations.AlterField(
            model_name="personalinfo",
            name="family_members",
            field=models.CharField(
                blank=True, max_length=512, verbose_name="Члены семьи"
            ),
        ),
        migrations.AlterField(
            model_name="personalinfo",
            name="family_status",
            field=models.CharField(
                blank=True, max_length=512, verbose_name="Семейное положение"
            ),
        ),
        migrations.AlterField(
            model_name="personalinfo",
            name="medical_report",
            field=models.TextField(blank=True, verbose_name="Врачебное заключение"),
        ),
        migrations.AlterField(
            model_name="personalinfo",
            name="passport_code",
            field=models.CharField(
                blank=True, max_length=4, verbose_name="Серия паспорта"
            ),
        ),
        migrations.AlterField(
            model_name="personalinfo",
            name="passport_issued",
            field=models.CharField(
                blank=True, max_length=512, verbose_name="Кем выдан паспорт"
            ),
        ),
        migrations.AlterField(
            model_name="personalinfo",
            name="passport_issued_date",
            field=models.DateField(
                blank=True, null=True, verbose_name="Дата выдачи паспорта"
            ),
        ),
        migrations.AlterField(
            model_name="personalinfo",
            name="passport_number",
            field=models.CharField(
                blank=True, max_length=6, verbose_name="Номер паспорта"
            ),
        ),
        migrations.AlterField(
            model_name="personalinfo",
            name="reg_address",
            field=models.CharField(
                blank=True, max_length=512, verbose_name="Адрес регистрации"
            ),
        ),
        migrations.AlterField(
            model_name="personalinfo",
            name="service_rank",
            field=models.CharField(
                blank=True, max_length=100, verbose_name="Служба в ВС, звание"
            ),
        ),
        migrations.AlterField(
            model_name="personalinfo",
            name="start_date",
            field=models.DateField(
                blank=True, null=True, verbose_name="Начало обучения"
            ),
        ),
        migrations.AlterField(
            model_name="personalinfo",
            name="student",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                to="journal.Student",
                verbose_name="Студент",
            ),
        ),
    ]
