# Generated by Django 2.2.4 on 2019-11-08 10:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("journal", "0016_manual_update_attendance"),
    ]

    operations = [
        migrations.RenameField(
            model_name="studentattendance",
            old_name="new_type",
            new_name="value",
        ),
        migrations.RemoveField(
            model_name="studentattendance",
            name="type",
        ),
    ]
