# Generated by Django 2.2.4 on 2019-11-08 10:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("journal", "0017_auto_20191108_1003"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="studentattendancetype",
            options={"managed": True},
        ),
    ]
