# Generated by Django 2.2.4 on 2019-11-15 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("journal", "0021_exams_20191115_0655"),
    ]

    operations = [
        migrations.AlterField(
            model_name="event",
            name="date",
            field=models.DateField(verbose_name="Дата"),
        ),
        migrations.DeleteModel(
            name="Final",
        ),
    ]
