# Generated by Django 2.2.4 on 2019-11-20 10:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("journal", "0022_auto_20191120_0927"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="penalty",
            name="date",
        ),
    ]
