# Generated by Django 2.2.4 on 2019-11-15 07:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("journal", "0024_auto_20191115_0717"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="mark",
            name="teacher",
        ),
    ]
