# Generated by Django 2.2.4 on 2019-11-20 12:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("journal", "0023_remove_penalty_date"),
        ("journal", "0025_remove_mark_teacher"),
    ]

    operations = []
