# Generated by Django 2.2.4 on 2019-11-15 10:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('journal', '0026_auto_20191115_1037'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lesson',
            name='squad',
        ),
    ]
