# Generated by Django 2.2.4 on 2019-11-22 07:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("journal", "0032_lesson_exam"),
        ("journal", "0026_merge_20191120_1259"),
    ]

    operations = []
