# Generated by Django 2.2.6 on 2019-11-29 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journal', '0035_auto_20191129_0829'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='pic',
            field=models.ImageField(null=True, upload_to='students_pic'),
        ),
    ]
