# Generated by Django 2.2.8 on 2019-12-13 08:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("journal", "0039_auto_20191211_0739"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="attendance",
            options={
                "managed": True,
                "verbose_name": "Строевая записка",
                "verbose_name_plural": "Строевая записка",
            },
        ),
        migrations.AlterField(
            model_name="attendance",
            name="squad",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="journal.Squad",
                verbose_name="Взвод",
            ),
        ),
        migrations.AlterField(
            model_name="attendance",
            name="students",
            field=models.ManyToManyField(
                to="journal.StudentAttendance", verbose_name="Студенты"
            ),
        ),
        migrations.AlterField(
            model_name="curriculum",
            name="squad",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="journal.Squad",
                verbose_name="Взвод",
            ),
        ),
        migrations.AlterField(
            model_name="curriculum",
            name="subject",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="journal.Subject",
                verbose_name="Предмет",
            ),
        ),
        migrations.AlterField(
            model_name="event",
            name="name",
            field=models.CharField(max_length=100, verbose_name="Название"),
        ),
        migrations.AlterField(
            model_name="eventparticipant",
            name="event",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="journal.Event",
                verbose_name="Мероприятие",
            ),
        ),
        migrations.AlterField(
            model_name="eventparticipant",
            name="student",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="journal.Student",
                verbose_name="Студент",
            ),
        ),
        migrations.AlterField(
            model_name="exam",
            name="subject",
            field=models.ForeignKey(
                db_column="subject",
                on_delete=django.db.models.deletion.CASCADE,
                to="journal.Subject",
                verbose_name="Предмет",
            ),
        ),
        migrations.AlterField(
            model_name="lesson",
            name="attendance",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="journal.Attendance",
                verbose_name="Строевая записка",
            ),
        ),
        migrations.AlterField(
            model_name="lesson",
            name="subject",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="journal.Subject",
                verbose_name="Предмет",
            ),
        ),
        migrations.AlterField(
            model_name="mark",
            name="lesson",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="journal.Lesson",
                verbose_name="Предмет",
            ),
        ),
        migrations.AlterField(
            model_name="mark",
            name="val",
            field=models.IntegerField(blank=True, null=True, verbose_name="Оценка"),
        ),
        migrations.AlterField(
            model_name="penalty",
            name="attendance",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="journal.Attendance",
                verbose_name="Строевая записка",
            ),
        ),
        migrations.AlterField(
            model_name="penalty",
            name="student",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="journal.Student",
                verbose_name="Студент",
            ),
        ),
        migrations.AlterField(
            model_name="squad",
            name="code",
            field=models.CharField(
                blank=True, max_length=4, null=True, unique=True, verbose_name="Номер"
            ),
        ),
        migrations.AlterField(
            model_name="student",
            name="pic",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to="students_pic/",
                verbose_name="Изображение",
            ),
        ),
    ]
