# Generated by Django 2.2.8 on 2019-12-20 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("journal", "0041_auto_20191220_0758"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userextension",
            name="squads",
            field=models.ManyToManyField(blank=True, to="journal.Squad"),
        ),
    ]
