# Generated by Django 2.2.8 on 2020-01-29 08:17

from django.db import migrations, models
import django.db.models.deletion

from _collections import defaultdict


def curriculum_to_timetable(apps, schema_editor):
    TimeTable = apps.get_model('journal', 'TimeTable')

    from django.db import connection
    cursor = connection.cursor()
    cursor.execute('''SELECT squad_id, subject_id FROM curriculum''')
    curriculums = cursor.fetchall()

    grouped_by_squad = defaultdict(list)
    for curr in curriculums:
        grouped_by_squad[curr[0]].append(curr[1])

    for squad, subjects in grouped_by_squad.items():
        print(squad, ':', subjects)

        tt_obj = TimeTable.objects.create(squad_id=squad)
        tt_obj.subjects.add(*subjects)


class Migration(migrations.Migration):

    dependencies = [
        ('journal', '0046_userextension_can_edit_attendance'),
    ]

    operations = [
        migrations.CreateModel(
            name='TimeTable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('squad', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='journal.Squad', verbose_name='Взвод')),
                ('subjects', models.ManyToManyField(blank=True, to='journal.Subject', verbose_name='Предметы')),
            ],
            options={
                'verbose_name': 'Расписание',
                'verbose_name_plural': 'Расписание',
                'db_table': 'timetable',
                'managed': True,
            },
        ),

        migrations.RunPython(curriculum_to_timetable),

        migrations.DeleteModel(
            name='Curriculum',
        ),
    ]
